### ISSUE TITLE
xform_brain should not require an explicit target specification for image data

### ISSUE THREAD

**Issue by jefferis** [jefferislab/nat.templatebrains#16]
Error:

> xform_brain("/Volumes/teraraid/flybrain/Shahar/SplitRegistration/IS2/reformatted/IS2_JK733SF457-1_02_warp_m0g80c8e1e-1x26r4.nrrd", ref=JFRC2, sample=IS2, outfile=path.expand("~/projects/Shahar/Screen/AdditionalOutputs/JFRC2_IS2_JK733SF457-1_02_warp_m0g80c8e1e-1x26r4.nrrd"))

Error in basename(as.character(f)) : 
  argument "target" is missing, with no default

OK:

> xform_brain("/Volumes/teraraid/flybrain/Shahar/SplitRegistration/IS2/reformatted/IS2_JK733SF457-1_02_warp_m0g80c8e1e-1x26r4.nrrd", ref=JFRC2, sample=IS2, target=JFRC2, outfile=path.expand("~/projects/Shahar/Screen/AdditionalOutputs/JFRC2_IS2_JK733SF457-1_02_warp_m0g80c8e1e-1x26r4.nrrd"))
> Reading transformation from studylist /Library/Frameworks/R.framework/Versions/3.2/Resources/library/nat.flybrains/extdata/bridgingregistrations/JFRC2_IS2.list
> WARNING: image does not have valid orientation meta information; cannot reorient.
> cmd:
>  '/usr/local/lib/cmtk/bin/reformatx' --verbose --outfile '/Volumes/teraraid/flybrain/Shahar/SplitRegistration/IS2/reformatted/JFRC2_IS2_JK733SF457-1_02_warp_m0g80c8e1e-1x26r4.nrrd' --floating '/Volumes/teraraid/flybrain/Shahar/SplitRegistration/IS2/reformatted/IS2_JK733SF457-1_02_warp_m0g80c8e1e-1x26r4.nrrd' --interpolation linear --outfile '/Volumes/teraraid/flybrain/Shahar/SplitRegistration/IS2/reformatted/JFRC2_IS2_JK733SF457-1_02_warp_m0g80c8e1e-1x26r4.nrrd' --target-grid 1024,512,218:0.622088,0.622088,0.622088:0.000000,0.000000,0.000000  '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/nat.flybrains/extdata/bridgingregistrations/JFRC2_IS2.list' 

(moved from https://github.com/jefferislab/nat.flybrains/issues/30)

**Comment by jefferis** [comment]
Could do this by adding a target argument (which is sometimes ignored) or modifying ...

see http://stackoverflow.com/questions/16321760/r-change-value-of-an-argument-in-ellipsis-and-pass-ellipsis-to-the-other-functi
for how to do that.

**Comment by jefferis** [comment]
@rrbenton this is a bug that you would like closed.

**Comment by jefferis** [comment]
@mmc46 this is interesting for you as well. Do you want to check 

```
devtools::install_github("jefferislab/nat.templatebrains@ feature/auto-target")
```
and see if it works for your use case without having to specify `target` explicitly.

**Comment by mmc46** [comment]
Yes, that works!
