### ISSUE TITLE
fix downloading of git repos when no git user has been set

### ISSUE THREAD

**Issue by jefferis** [jefferislab/nat.templatebrains#20]
This seems to be a Windows specific issue and manifests like this:

```
> nat.flybrains::download_jefferislab_registrations()
Error in default_signature(repo) : 
  Error in 'git2r_signature_default': Failed to parse signature - Signature cannot have an empty name or email
```

when no git user has been set (one seems to be made up on mac).

**Comment by jefferis** [comment]
Hold off on that submission @ajdm, one more fix required!

**Comment by jefferis** [comment]
OK @ajdm, this tested OK on Windows so I think we are good to go to prepare a bugfix release for CRAN. Thanks! G.

**Comment by ajdm** [comment]
There's one issue in that the version of nat available on CRAN is 
insufficient on Mac OS X 
(https://cran.r-project.org/web/checks/check_results_nat.templatebrains.html). 
Do we just ignore and see if Ripley et al will take it anyway?

**Comment by jefferis** [comment]
As usual an rgl problem. Don't know why the build machine can't reliably have this. I am considering having nat check on load whether it is running interactive and, if yes, setting rglUSENULL to T. There is a branch for this on nat's GitHub. Thoughts? G.

**Comment by ajdm** [comment]
It looks like they're not going to fix the rgl issues any time soon, so 
I reckon that's a good idea.

**Comment by jefferis** [comment]
Do you want to try that nat branch out then, maybe merge it into master? It seems fairly straightforward. I guess my only concern is that I might have overlooked something when running batch jobs eg the NBLAST server. G.

**Comment by ajdm** [comment]
Okay, I'll give that a go. In the mean time, I've submitted as is to CRAN,
as I think they'll take it anyway.

**Comment by ajdm** [comment]
On CRAN now.
