### ISSUE TITLE
Reducing alpha of segmented surface template brains slows interactivity

### ISSUE THREAD

**Issue by josesho** [jefferislab/nat.templatebrains#22]
When the alpha of a segmented surface brain is reduced, it is difficult to interact with the 3D rendering -- rotating and panning become extremely laggy.

```{r}
library('nat')
library('nat.flybrains')

nopen3d()
plot3d(FCWBNP.surf) # Display the segment FCWB surface model as per default. Interactivity is OK.
par3d(windowRect=c(0,0,1024,768)) # Make the X11 window larger.

nopen3d()
plot3d(FCWBNP.surf, alpha = 0.5) # Display the segment FCWB surface model, with reduced opacity.
par3d(windowRect=c(0,0,1024,768)) # Make the X11 window larger.
# Note how laggy the interactive window becomes.
```

Any ways to mitigate the lag? I observe the lag both on a 27" mid-2010 iMac, and a 15" late-2013 MacBook Pro.

```{r}
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] nat.flybrains_1.6        nat.templatebrains_0.6.2 nat_1.7.2                rgl_0.95.1435           

loaded via a namespace (and not attached):
 [1] magrittr_1.5     tools_3.2.2      igraph_1.0.1     rappdirs_0.3     yaml_2.1.13      nat.utils_0.5.1 
 [7] Rcpp_0.12.3      filehash_2.3     codetools_0.2-14 nabor_0.4.6      digest_0.6.9    
```

**Comment by ajdm** [comment]
Unfortunately not, as far as I'm aware. This seems to be an RGL issue, in that plotting anything overlapping with ``alpha != 1`` causes a slowdown (even ``nopen3d(); plot3d(FCWB); plot3d(JFRC2)`` will cause one). If you do find a way of mitigating the issue please let me know and I'll try and implement it.

**Comment by jefferis** [comment]
From my own experience, I would not recommend using the full neuropil segmentations with alpha transparency. This seems to pushing the limit of rgl. I generally use a combination of the full brain along with a subset of the neuropils and that is acceptable.

**Comment by josesho** [comment]
So just pull out the desired neuropils from a segmented template and plot those in 3D?

**Comment by jefferis** [comment]
> So just pull out the desired neuropils from a segmented template and plot those in 3D?

Exactly. It's actually very easy to do with the subset argument of `plot3d.hxsurf` which specifies a regex matching neuropil abbreviations. For example

```r
#plot all the MB neuropil subdivisions (lobes, calyx and peduncle)
plot3d(JFRC2NP.surf, "MB") 
#plot AL and LH on fly's left
plot3d(JFRC2NP.surf, "(AL|LH)_L") 
```
You can also use `subset.hxsurf` to extract those neuropils if you need and `as.mesh3d` to convert them if needed for additional computation using **rgl** or packages like **Rvcg**, **Morpho** and **mesher**.

**Comment by jefferis** [comment]
Here's an example with those settings. Might want to make the neurons a bit heaver (e.g. `lwd=2`).

![vpns](https://cloud.githubusercontent.com/assets/23763/13247139/b7695612-da0f-11e5-9e4d-6aadb0de8842.png)
