### ISSUE TITLE
Uninformative error from CMTK with kcs20 example

### ISSUE THREAD

**Issue by r-shruthi11** [jefferislab/nat.templatebrains#38]
I'm trying to replicate the example that accompanies the xform_brain documentation here:  https://www.rdocumentation.org/packages/nat.templatebrains/versions/0.9/topics/xform_brain and when I try to execute `xform_brain(kcs20, sample=FCWB, reference=JFRC2, .progrexx='text)` I see this error `Error in cmtk.streamxform(points,reg,direction,transformtype): Error running CMTK streamxform!` 
Please advice on how to proceed since this error is uninformative and doesn't tell me where the function seems to be failing

**Comment by jefferis** [comment]
Hmm, I agree that the message could be better since I can’t immediately guess it’s origin. However I do see that you have a typo in the .progress argument. Should end in as not xx.

**Comment by jefferis** [comment]
Can I check if you have actually installed CMTK? What does `cmtk.bindir()` return?

**Comment by r-shruthi11** [comment]
Sorry, this was a typo in my comment, the command in R itself spelled progress appropriately. `cmtk.bindir()` returns ` "C:\\cygwin64\\usr\\local\\lib\\cmtk\\bin"`

**Comment by jefferis** [comment]
Ok. Can you tell me what you get from `cmtk.dof2mat(version = TRUE)`. This actually checks if one of the CMTK tools can be run.

**Comment by r-shruthi11** [comment]
This command gave me an error. I reinstalled CMTK and that seems to have solved the issue. Thanks a lot for the help!

**Comment by jefferis** [comment]
Great! I think that in the circumstances the error message was not far off – the CMTK tool could not be run. We could maybe look into some kind of function that can check the CMTK setup. @SridharJagannathan perhaps we could make a function like `natverse::dr_nat` that checks if CMTK is installed and runnable and perhaps looks at other things like whether bridging registrations have been downloaded etc.
