### ISSUE TITLE
Use rappdirs for storing registrations?

### ISSUE THREAD

**Issue by ajdm** [jefferislab/nat.templatebrains#6]
Rather than having registrations in various places, such as each helper package's (e.g. [nat.flybrains](https://github.com/jefferislab/nat.flybrains)) ``extdata`` folder, should we instead use [rappdirs](https://github.com/hadley/rappdirs) to store registrations, with each helper package creating a sub-directory within this? This would then make it easier for users to add registrations without having to create a whole new R package.

**Comment by jefferis** [comment]
Some related work using rappdirs in nat.flybrains was merged here: https://github.com/jefferislab/nat.flybrains/commit/f4df0234563b91158243af626ec9e3c9169bf34d

**Comment by jefferis** [comment]
When this is stable, it would make sense to move from nat.flybrains to nat.templatebrains. However there will be a decision to make about 
1. what level hierarchy to use (e.g. include github user name)
2. whether to associate registrations with a specific package
3. whether to add registrations to the ones considered on package load

**Comment by jefferis** [comment]
This is now implemented in nat.templatebrains as of v0.6. See e.g. commit 48789aa28a02650459678e26e464a36a21971a6d
